name-template: 'v$RESOLVED_VERSION 🌈'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'bug'
  - title: '📚 Documentation'
    labels:
      - 'documentation'
  - title: '🧰 Maintenance'
    labels:
      - 'chore'
  - title: '🤖 Dependencies'
    labels:
      - 'dependencies'
change-template: '- $TITLE (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - 'semver:major'
  minor:
    labels:
      - 'semver:minor'
  patch:
    labels:
      - 'semver:patch'
  default: patch
template: |
  ## Changes

  $CHANGES
