_extends: LYS-42:.github/release-drafter.base.yml
name-template: random-pair-colors@$RESOLVED_VERSION
tag-template: random-pair-colors@$RESOLVED_VERSION
tag-prefix: random-pair-colors@
include-paths:
  - "packages/random-pair-colors/"