# act workflow_dispatch -W .github/workflows/ci.yml --container-architecture linux/amd64
name: ci
on:
  workflow_dispatch:
  pull_request:
    paths:
      - '.github/workflows/ci.yml'
      - 'packages/focus-pair-reader/**'
      - 'packages/random-pair-colors/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: npm
    - run: npm ci
    - run: npm run biome:ci
  build:
    strategy:
      matrix:
       packages: ['packages/focus-pair-reader', 'packages/random-pair-colors']
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: npm
    - run: npm ci
    - run: npm -w ${{ matrix.packages }} run build
