name: Publish Package to @lys-42/random-pair-colors

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - '**'
    tags:
      - 'random-pair-colors@*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - run: npm -w @lys-42/random-pair-colors run build
      - run: npm -w @lys-42/random-pair-colors publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
