name: Publish Package to @ergofriend/focus-pair-reader

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - '**'
    tags:
      - 'focus-pair-reader@*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - run: npm -w @ergofriend/focus-pair-reader run build
      - run: npm -w @ergofriend/focus-pair-reader publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
