name: Release Drafter

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  contents: read

jobs:
  update_release_draft:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Draft random-pair-colors release
        uses: release-drafter/release-drafter@v5
        with:
          config-name: release-drafter.random-pair-colors.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Draft focus-pair-reader release
        uses: release-drafter/release-drafter@v5
        with:
          config-name: release-drafter.focus-pair-reader.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
