name: Require Labels
on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]
    paths:
      - 'packages/**'

jobs:
  label:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: Semver label
        uses: mheap/github-action-required-labels@v5
        with:
          mode: exactly
          count: 1
          labels: "semver:patch, semver:minor, semver:major"
      - name: Category label
        uses: mheap/github-action-required-labels@v5
        with:
          mode: exactly
          count: 1
          labels: "enhancement, bug, documentation, chore, dependencies"
